language: node_js

node_js:
  - "0.10"
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

before_install:
  # Update npm to 2.x
  - npm install -g npm@2

install:
  - travis_retry npm install --silent
  - travis_retry bower install --silent

# now run the tests!
script:
  - npm test
  - npm run lint
